package com.supermarket.dao;

import com.supermarket.model.Product;
import com.supermarket.utility.DatabaseConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ProductDAOImpl implements ProductDAO {
    private DatabaseConnection databaseConnection;

    public ProductDAOImpl(DatabaseConnection databaseConnection) {
        this.databaseConnection = databaseConnection;
    }
    public boolean insertProduct(Product product) {
        // SQL command to insert a product into the database
//        id is autogenerated in the table
        String sql = "INSERT INTO products (product_name,category,price,quantity) VALUES (?,?,?,?)";
        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, product.getName());
            statement.setString(2, product.getCategory());
            statement.setDouble(3, product.getPrice());
            statement.setInt(4,product.getQuantity());
            int rowsInserted = statement.executeUpdate();
            return rowsInserted > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
}
